apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: omni-obs
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging:
        verbosity: detailed
    extensions:
      health_check:
    service:
      extensions: [health_check]
      telemetry:
        metrics:
          level: detailed
          address: 0.0.0.0:8888
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus, logging]
        traces:
          receivers: [otlp]
          exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: omni-obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.96.0
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 13133
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otelcol-contrib/
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
          items:
            - key: otel-config.yaml
              path: config.yaml
