apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omni-obs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kanim21/omni-obs-platform.git
    targetRevision: main
    path: kubernetes/overlays/single
  destination:
    server: https://kubernetes.default.svc
    namespace: omni-obs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
